# fly.toml app configuration file generated for spliit-cloud on 2026-07-25T18:01:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spliit-cloud'
primary_region = 'fra'
kill_signal = 'SIGTERM'
kill_timeout = '40s'

[build]
  dockerfile = 'Dockerfile'
  build-target = 'api'

  [build.args]
    APP_SCOPE = '@spliit/api'

[deploy]
  release_command = 'bun run --filter @spliit/db prisma-migrate'

[env]
  JOBS_INLINE = 'true'
  JOBS_RECONCILIATION_CRON = '0 * * * *'
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health/readiness'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
