/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GroupsRouteRouteImport } from './routes/groups/route'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthRecoverRouteImport } from './routes/auth/recover'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as FriendsCreateRouteImport } from './routes/friends/create'
import { Route as GroupsGroupIdRouteRouteImport } from './routes/groups/$groupId/route'
import { Route as GroupsCreateRouteImport } from './routes/groups/create'
import { Route as GroupsImportRouteImport } from './routes/groups/import'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as OauthLoginRouteImport } from './routes/oauth/login'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdActivityRouteImport } from './routes/groups/$groupId/activity'
import { Route as GroupsGroupIdBalancesRouteImport } from './routes/groups/$groupId/balances'
import { Route as GroupsGroupIdBudgetsRouteImport } from './routes/groups/$groupId/budgets'
import { Route as GroupsGroupIdEditRouteImport } from './routes/groups/$groupId/edit'
import { Route as GroupsGroupIdExpensesRouteImport } from './routes/groups/$groupId/expenses'
import { Route as GroupsGroupIdInformationRouteImport } from './routes/groups/$groupId/information'
import { Route as GroupsGroupIdMembersRouteImport } from './routes/groups/$groupId/members'
import { Route as GroupsGroupIdStatsRouteImport } from './routes/groups/$groupId/stats'
import { Route as GroupsBulkCategorizeGroupIdRouteImport } from './routes/groups/bulk-categorize/$groupId'
import { Route as GroupsGroupIdBudgetsIndexRouteImport } from './routes/groups/$groupId/budgets/index'
import { Route as GroupsGroupIdExpensesIndexRouteImport } from './routes/groups/$groupId/expenses/index'
import { Route as GroupsGroupIdExpensesCreateRouteImport } from './routes/groups/$groupId/expenses/create'
import { Route as GroupsGroupIdExpensesPrintRouteImport } from './routes/groups/$groupId/expenses/print'
import { Route as GroupsGroupIdExpensesExpenseIdIndexRouteImport } from './routes/groups/$groupId/expenses/$expenseId/index'
import { Route as GroupsGroupIdExpensesExpenseIdEditRouteImport } from './routes/groups/$groupId/expenses/$expenseId/edit'

const GroupsGroupIdBudgetsCreateLazyRouteImport = createFileRoute(
  '/groups/$groupId/budgets/create',
)()
const GroupsGroupIdBudgetsBudgetIdIndexLazyRouteImport = createFileRoute(
  '/groups/$groupId/budgets/$budgetId/',
)()
const GroupsGroupIdBudgetsBudgetIdEditLazyRouteImport = createFileRoute(
  '/groups/$groupId/budgets/$budgetId/edit',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/expenses.lazy').then((d) => d.Route))
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/feedback.lazy').then((d) => d.Route))
const GroupsRouteRoute = GroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/groups/route.lazy').then((d) => d.Route))
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/imprint.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/unsubscribe.lazy').then((d) => d.Route))
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/account/settings.lazy').then((d) => d.Route),
)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/complete-profile.lazy').then((d) => d.Route),
)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/forgot-password.lazy').then((d) => d.Route),
)
const AuthRecoverRoute = AuthRecoverRouteImport.update({
  id: '/auth/recover',
  path: '/auth/recover',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/recover.lazy').then((d) => d.Route))
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/auth/reset-password.lazy').then((d) => d.Route),
)
const FriendsCreateRoute = FriendsCreateRouteImport.update({
  id: '/friends/create',
  path: '/friends/create',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/friends/create.lazy').then((d) => d.Route),
)
const GroupsGroupIdRouteRoute = GroupsGroupIdRouteRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GroupsRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/route.lazy').then((d) => d.Route),
)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => GroupsRouteRoute,
} as any).lazy(() => import('./routes/groups/create.lazy').then((d) => d.Route))
const GroupsImportRoute = GroupsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => GroupsRouteRoute,
} as any).lazy(() => import('./routes/groups/import.lazy').then((d) => d.Route))
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/oauth/consent.lazy').then((d) => d.Route))
const OauthLoginRoute = OauthLoginRouteImport.update({
  id: '/oauth/login',
  path: '/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/oauth/login.lazy').then((d) => d.Route))
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/index.lazy').then((d) => d.Route),
)
const GroupsGroupIdActivityRoute = GroupsGroupIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/activity.lazy').then((d) => d.Route),
)
const GroupsGroupIdBalancesRoute = GroupsGroupIdBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/balances.lazy').then((d) => d.Route),
)
const GroupsGroupIdBudgetsRoute = GroupsGroupIdBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/budgets.lazy').then((d) => d.Route),
)
const GroupsGroupIdEditRoute = GroupsGroupIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/edit.lazy').then((d) => d.Route),
)
const GroupsGroupIdExpensesRoute = GroupsGroupIdExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/expenses.lazy').then((d) => d.Route),
)
const GroupsGroupIdInformationRoute =
  GroupsGroupIdInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => GroupsGroupIdRouteRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/information.lazy').then((d) => d.Route),
  )
const GroupsGroupIdMembersRoute = GroupsGroupIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/members.lazy').then((d) => d.Route),
)
const GroupsGroupIdStatsRoute = GroupsGroupIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any).lazy(() =>
  import('./routes/groups/$groupId/stats.lazy').then((d) => d.Route),
)
const GroupsBulkCategorizeGroupIdRoute =
  GroupsBulkCategorizeGroupIdRouteImport.update({
    id: '/bulk-categorize/$groupId',
    path: '/bulk-categorize/$groupId',
    getParentRoute: () => GroupsRouteRoute,
  } as any).lazy(() =>
    import('./routes/groups/bulk-categorize/$groupId.lazy').then(
      (d) => d.Route,
    ),
  )
const GroupsGroupIdBudgetsIndexRoute =
  GroupsGroupIdBudgetsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GroupsGroupIdBudgetsRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/budgets/index.lazy').then((d) => d.Route),
  )
const GroupsGroupIdBudgetsCreateLazyRoute =
  GroupsGroupIdBudgetsCreateLazyRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => GroupsGroupIdBudgetsRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/budgets/create.lazy').then((d) => d.Route),
  )
const GroupsGroupIdExpensesIndexRoute =
  GroupsGroupIdExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GroupsGroupIdExpensesRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/expenses/index.lazy').then((d) => d.Route),
  )
const GroupsGroupIdExpensesCreateRoute =
  GroupsGroupIdExpensesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => GroupsGroupIdExpensesRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/expenses/create.lazy').then(
      (d) => d.Route,
    ),
  )
const GroupsGroupIdExpensesPrintRoute =
  GroupsGroupIdExpensesPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => GroupsGroupIdExpensesRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/expenses/print.lazy').then((d) => d.Route),
  )
const GroupsGroupIdBudgetsBudgetIdIndexLazyRoute =
  GroupsGroupIdBudgetsBudgetIdIndexLazyRouteImport.update({
    id: '/$budgetId/',
    path: '/$budgetId/',
    getParentRoute: () => GroupsGroupIdBudgetsRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/budgets/$budgetId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const GroupsGroupIdBudgetsBudgetIdEditLazyRoute =
  GroupsGroupIdBudgetsBudgetIdEditLazyRouteImport.update({
    id: '/$budgetId/edit',
    path: '/$budgetId/edit',
    getParentRoute: () => GroupsGroupIdBudgetsRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/budgets/$budgetId/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const GroupsGroupIdExpensesExpenseIdIndexRoute =
  GroupsGroupIdExpensesExpenseIdIndexRouteImport.update({
    id: '/$expenseId/',
    path: '/$expenseId/',
    getParentRoute: () => GroupsGroupIdExpensesRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/expenses/$expenseId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const GroupsGroupIdExpensesExpenseIdEditRoute =
  GroupsGroupIdExpensesExpenseIdEditRouteImport.update({
    id: '/$expenseId/edit',
    path: '/$expenseId/edit',
    getParentRoute: () => GroupsGroupIdExpensesRoute,
  } as any).lazy(() =>
    import('./routes/groups/$groupId/expenses/$expenseId/edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRouteRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/friends/create': typeof FriendsCreateRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/import': typeof GroupsImportRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/groups/$groupId/activity': typeof GroupsGroupIdActivityRoute
  '/groups/$groupId/balances': typeof GroupsGroupIdBalancesRoute
  '/groups/$groupId/budgets': typeof GroupsGroupIdBudgetsRouteWithChildren
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
  '/groups/$groupId/expenses': typeof GroupsGroupIdExpensesRouteWithChildren
  '/groups/$groupId/information': typeof GroupsGroupIdInformationRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/stats': typeof GroupsGroupIdStatsRoute
  '/groups/bulk-categorize/$groupId': typeof GroupsBulkCategorizeGroupIdRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/create': typeof GroupsGroupIdExpensesCreateRoute
  '/groups/$groupId/expenses/print': typeof GroupsGroupIdExpensesPrintRoute
  '/groups/$groupId/budgets/create': typeof GroupsGroupIdBudgetsCreateLazyRoute
  '/groups/$groupId/budgets/': typeof GroupsGroupIdBudgetsIndexRoute
  '/groups/$groupId/expenses/': typeof GroupsGroupIdExpensesIndexRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
  '/groups/$groupId/budgets/$budgetId/edit': typeof GroupsGroupIdBudgetsBudgetIdEditLazyRoute
  '/groups/$groupId/expenses/$expenseId/': typeof GroupsGroupIdExpensesExpenseIdIndexRoute
  '/groups/$groupId/budgets/$budgetId/': typeof GroupsGroupIdBudgetsBudgetIdIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRouteRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/friends/create': typeof FriendsCreateRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/import': typeof GroupsImportRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/groups/$groupId/activity': typeof GroupsGroupIdActivityRoute
  '/groups/$groupId/balances': typeof GroupsGroupIdBalancesRoute
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
  '/groups/$groupId/information': typeof GroupsGroupIdInformationRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/stats': typeof GroupsGroupIdStatsRoute
  '/groups/bulk-categorize/$groupId': typeof GroupsBulkCategorizeGroupIdRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/create': typeof GroupsGroupIdExpensesCreateRoute
  '/groups/$groupId/expenses/print': typeof GroupsGroupIdExpensesPrintRoute
  '/groups/$groupId/budgets/create': typeof GroupsGroupIdBudgetsCreateLazyRoute
  '/groups/$groupId/budgets': typeof GroupsGroupIdBudgetsIndexRoute
  '/groups/$groupId/expenses': typeof GroupsGroupIdExpensesIndexRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
  '/groups/$groupId/budgets/$budgetId/edit': typeof GroupsGroupIdBudgetsBudgetIdEditLazyRoute
  '/groups/$groupId/expenses/$expenseId': typeof GroupsGroupIdExpensesExpenseIdIndexRoute
  '/groups/$groupId/budgets/$budgetId': typeof GroupsGroupIdBudgetsBudgetIdIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRouteRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/feedback': typeof FeedbackRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/recover': typeof AuthRecoverRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/friends/create': typeof FriendsCreateRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/import': typeof GroupsImportRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/groups/$groupId/activity': typeof GroupsGroupIdActivityRoute
  '/groups/$groupId/balances': typeof GroupsGroupIdBalancesRoute
  '/groups/$groupId/budgets': typeof GroupsGroupIdBudgetsRouteWithChildren
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
  '/groups/$groupId/expenses': typeof GroupsGroupIdExpensesRouteWithChildren
  '/groups/$groupId/information': typeof GroupsGroupIdInformationRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/stats': typeof GroupsGroupIdStatsRoute
  '/groups/bulk-categorize/$groupId': typeof GroupsBulkCategorizeGroupIdRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/create': typeof GroupsGroupIdExpensesCreateRoute
  '/groups/$groupId/expenses/print': typeof GroupsGroupIdExpensesPrintRoute
  '/groups/$groupId/budgets/create': typeof GroupsGroupIdBudgetsCreateLazyRoute
  '/groups/$groupId/budgets/': typeof GroupsGroupIdBudgetsIndexRoute
  '/groups/$groupId/expenses/': typeof GroupsGroupIdExpensesIndexRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
  '/groups/$groupId/budgets/$budgetId/edit': typeof GroupsGroupIdBudgetsBudgetIdEditLazyRoute
  '/groups/$groupId/expenses/$expenseId/': typeof GroupsGroupIdExpensesExpenseIdIndexRoute
  '/groups/$groupId/budgets/$budgetId/': typeof GroupsGroupIdBudgetsBudgetIdIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/expenses'
    | '/feedback'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/unsubscribe'
    | '/groups/$groupId'
    | '/account/settings'
    | '/auth/complete-profile'
    | '/auth/forgot-password'
    | '/auth/recover'
    | '/auth/reset-password'
    | '/friends/create'
    | '/groups/create'
    | '/groups/import'
    | '/oauth/consent'
    | '/oauth/login'
    | '/groups/$groupId/activity'
    | '/groups/$groupId/balances'
    | '/groups/$groupId/budgets'
    | '/groups/$groupId/edit'
    | '/groups/$groupId/expenses'
    | '/groups/$groupId/information'
    | '/groups/$groupId/members'
    | '/groups/$groupId/stats'
    | '/groups/bulk-categorize/$groupId'
    | '/groups/$groupId/'
    | '/groups/$groupId/expenses/create'
    | '/groups/$groupId/expenses/print'
    | '/groups/$groupId/budgets/create'
    | '/groups/$groupId/budgets/'
    | '/groups/$groupId/expenses/'
    | '/groups/$groupId/expenses/$expenseId/edit'
    | '/groups/$groupId/budgets/$budgetId/edit'
    | '/groups/$groupId/expenses/$expenseId/'
    | '/groups/$groupId/budgets/$budgetId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/expenses'
    | '/feedback'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/unsubscribe'
    | '/account/settings'
    | '/auth/complete-profile'
    | '/auth/forgot-password'
    | '/auth/recover'
    | '/auth/reset-password'
    | '/friends/create'
    | '/groups/create'
    | '/groups/import'
    | '/oauth/consent'
    | '/oauth/login'
    | '/groups/$groupId/activity'
    | '/groups/$groupId/balances'
    | '/groups/$groupId/edit'
    | '/groups/$groupId/information'
    | '/groups/$groupId/members'
    | '/groups/$groupId/stats'
    | '/groups/bulk-categorize/$groupId'
    | '/groups/$groupId'
    | '/groups/$groupId/expenses/create'
    | '/groups/$groupId/expenses/print'
    | '/groups/$groupId/budgets/create'
    | '/groups/$groupId/budgets'
    | '/groups/$groupId/expenses'
    | '/groups/$groupId/expenses/$expenseId/edit'
    | '/groups/$groupId/budgets/$budgetId/edit'
    | '/groups/$groupId/expenses/$expenseId'
    | '/groups/$groupId/budgets/$budgetId'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/expenses'
    | '/feedback'
    | '/imprint'
    | '/privacy'
    | '/terms'
    | '/unsubscribe'
    | '/groups/$groupId'
    | '/account/settings'
    | '/auth/complete-profile'
    | '/auth/forgot-password'
    | '/auth/recover'
    | '/auth/reset-password'
    | '/friends/create'
    | '/groups/create'
    | '/groups/import'
    | '/oauth/consent'
    | '/oauth/login'
    | '/groups/$groupId/activity'
    | '/groups/$groupId/balances'
    | '/groups/$groupId/budgets'
    | '/groups/$groupId/edit'
    | '/groups/$groupId/expenses'
    | '/groups/$groupId/information'
    | '/groups/$groupId/members'
    | '/groups/$groupId/stats'
    | '/groups/bulk-categorize/$groupId'
    | '/groups/$groupId/'
    | '/groups/$groupId/expenses/create'
    | '/groups/$groupId/expenses/print'
    | '/groups/$groupId/budgets/create'
    | '/groups/$groupId/budgets/'
    | '/groups/$groupId/expenses/'
    | '/groups/$groupId/expenses/$expenseId/edit'
    | '/groups/$groupId/budgets/$budgetId/edit'
    | '/groups/$groupId/expenses/$expenseId/'
    | '/groups/$groupId/budgets/$budgetId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRouteRoute: typeof GroupsRouteRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  FeedbackRoute: typeof FeedbackRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthRecoverRoute: typeof AuthRecoverRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  FriendsCreateRoute: typeof FriendsCreateRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthLoginRoute: typeof OauthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recover': {
      id: '/auth/recover'
      path: '/auth/recover'
      fullPath: '/auth/recover'
      preLoaderRoute: typeof AuthRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/create': {
      id: '/friends/create'
      path: '/friends/create'
      fullPath: '/friends/create'
      preLoaderRoute: typeof FriendsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteRouteImport
      parentRoute: typeof GroupsRouteRoute
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof GroupsRouteRoute
    }
    '/groups/import': {
      id: '/groups/import'
      path: '/import'
      fullPath: '/groups/import'
      preLoaderRoute: typeof GroupsImportRouteImport
      parentRoute: typeof GroupsRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login': {
      id: '/oauth/login'
      path: '/oauth/login'
      fullPath: '/oauth/login'
      preLoaderRoute: typeof OauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/activity': {
      id: '/groups/$groupId/activity'
      path: '/activity'
      fullPath: '/groups/$groupId/activity'
      preLoaderRoute: typeof GroupsGroupIdActivityRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/balances': {
      id: '/groups/$groupId/balances'
      path: '/balances'
      fullPath: '/groups/$groupId/balances'
      preLoaderRoute: typeof GroupsGroupIdBalancesRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/budgets': {
      id: '/groups/$groupId/budgets'
      path: '/budgets'
      fullPath: '/groups/$groupId/budgets'
      preLoaderRoute: typeof GroupsGroupIdBudgetsRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/edit': {
      id: '/groups/$groupId/edit'
      path: '/edit'
      fullPath: '/groups/$groupId/edit'
      preLoaderRoute: typeof GroupsGroupIdEditRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/expenses': {
      id: '/groups/$groupId/expenses'
      path: '/expenses'
      fullPath: '/groups/$groupId/expenses'
      preLoaderRoute: typeof GroupsGroupIdExpensesRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/information': {
      id: '/groups/$groupId/information'
      path: '/information'
      fullPath: '/groups/$groupId/information'
      preLoaderRoute: typeof GroupsGroupIdInformationRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/members': {
      id: '/groups/$groupId/members'
      path: '/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/$groupId/stats': {
      id: '/groups/$groupId/stats'
      path: '/stats'
      fullPath: '/groups/$groupId/stats'
      preLoaderRoute: typeof GroupsGroupIdStatsRouteImport
      parentRoute: typeof GroupsGroupIdRouteRoute
    }
    '/groups/bulk-categorize/$groupId': {
      id: '/groups/bulk-categorize/$groupId'
      path: '/bulk-categorize/$groupId'
      fullPath: '/groups/bulk-categorize/$groupId'
      preLoaderRoute: typeof GroupsBulkCategorizeGroupIdRouteImport
      parentRoute: typeof GroupsRouteRoute
    }
    '/groups/$groupId/budgets/': {
      id: '/groups/$groupId/budgets/'
      path: '/'
      fullPath: '/groups/$groupId/budgets/'
      preLoaderRoute: typeof GroupsGroupIdBudgetsIndexRouteImport
      parentRoute: typeof GroupsGroupIdBudgetsRoute
    }
    '/groups/$groupId/budgets/create': {
      id: '/groups/$groupId/budgets/create'
      path: '/create'
      fullPath: '/groups/$groupId/budgets/create'
      preLoaderRoute: typeof GroupsGroupIdBudgetsCreateLazyRouteImport
      parentRoute: typeof GroupsGroupIdBudgetsRoute
    }
    '/groups/$groupId/expenses/': {
      id: '/groups/$groupId/expenses/'
      path: '/'
      fullPath: '/groups/$groupId/expenses/'
      preLoaderRoute: typeof GroupsGroupIdExpensesIndexRouteImport
      parentRoute: typeof GroupsGroupIdExpensesRoute
    }
    '/groups/$groupId/expenses/create': {
      id: '/groups/$groupId/expenses/create'
      path: '/create'
      fullPath: '/groups/$groupId/expenses/create'
      preLoaderRoute: typeof GroupsGroupIdExpensesCreateRouteImport
      parentRoute: typeof GroupsGroupIdExpensesRoute
    }
    '/groups/$groupId/expenses/print': {
      id: '/groups/$groupId/expenses/print'
      path: '/print'
      fullPath: '/groups/$groupId/expenses/print'
      preLoaderRoute: typeof GroupsGroupIdExpensesPrintRouteImport
      parentRoute: typeof GroupsGroupIdExpensesRoute
    }
    '/groups/$groupId/budgets/$budgetId/': {
      id: '/groups/$groupId/budgets/$budgetId/'
      path: '/$budgetId'
      fullPath: '/groups/$groupId/budgets/$budgetId/'
      preLoaderRoute: typeof GroupsGroupIdBudgetsBudgetIdIndexLazyRouteImport
      parentRoute: typeof GroupsGroupIdBudgetsRoute
    }
    '/groups/$groupId/budgets/$budgetId/edit': {
      id: '/groups/$groupId/budgets/$budgetId/edit'
      path: '/$budgetId/edit'
      fullPath: '/groups/$groupId/budgets/$budgetId/edit'
      preLoaderRoute: typeof GroupsGroupIdBudgetsBudgetIdEditLazyRouteImport
      parentRoute: typeof GroupsGroupIdBudgetsRoute
    }
    '/groups/$groupId/expenses/$expenseId/': {
      id: '/groups/$groupId/expenses/$expenseId/'
      path: '/$expenseId'
      fullPath: '/groups/$groupId/expenses/$expenseId/'
      preLoaderRoute: typeof GroupsGroupIdExpensesExpenseIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdExpensesRoute
    }
    '/groups/$groupId/expenses/$expenseId/edit': {
      id: '/groups/$groupId/expenses/$expenseId/edit'
      path: '/$expenseId/edit'
      fullPath: '/groups/$groupId/expenses/$expenseId/edit'
      preLoaderRoute: typeof GroupsGroupIdExpensesExpenseIdEditRouteImport
      parentRoute: typeof GroupsGroupIdExpensesRoute
    }
  }
}

interface GroupsGroupIdBudgetsRouteChildren {
  GroupsGroupIdBudgetsCreateLazyRoute: typeof GroupsGroupIdBudgetsCreateLazyRoute
  GroupsGroupIdBudgetsIndexRoute: typeof GroupsGroupIdBudgetsIndexRoute
  GroupsGroupIdBudgetsBudgetIdEditLazyRoute: typeof GroupsGroupIdBudgetsBudgetIdEditLazyRoute
  GroupsGroupIdBudgetsBudgetIdIndexLazyRoute: typeof GroupsGroupIdBudgetsBudgetIdIndexLazyRoute
}

const GroupsGroupIdBudgetsRouteChildren: GroupsGroupIdBudgetsRouteChildren = {
  GroupsGroupIdBudgetsCreateLazyRoute: GroupsGroupIdBudgetsCreateLazyRoute,
  GroupsGroupIdBudgetsIndexRoute: GroupsGroupIdBudgetsIndexRoute,
  GroupsGroupIdBudgetsBudgetIdEditLazyRoute:
    GroupsGroupIdBudgetsBudgetIdEditLazyRoute,
  GroupsGroupIdBudgetsBudgetIdIndexLazyRoute:
    GroupsGroupIdBudgetsBudgetIdIndexLazyRoute,
}

const GroupsGroupIdBudgetsRouteWithChildren =
  GroupsGroupIdBudgetsRoute._addFileChildren(GroupsGroupIdBudgetsRouteChildren)

interface GroupsGroupIdExpensesRouteChildren {
  GroupsGroupIdExpensesCreateRoute: typeof GroupsGroupIdExpensesCreateRoute
  GroupsGroupIdExpensesPrintRoute: typeof GroupsGroupIdExpensesPrintRoute
  GroupsGroupIdExpensesIndexRoute: typeof GroupsGroupIdExpensesIndexRoute
  GroupsGroupIdExpensesExpenseIdEditRoute: typeof GroupsGroupIdExpensesExpenseIdEditRoute
  GroupsGroupIdExpensesExpenseIdIndexRoute: typeof GroupsGroupIdExpensesExpenseIdIndexRoute
}

const GroupsGroupIdExpensesRouteChildren: GroupsGroupIdExpensesRouteChildren = {
  GroupsGroupIdExpensesCreateRoute: GroupsGroupIdExpensesCreateRoute,
  GroupsGroupIdExpensesPrintRoute: GroupsGroupIdExpensesPrintRoute,
  GroupsGroupIdExpensesIndexRoute: GroupsGroupIdExpensesIndexRoute,
  GroupsGroupIdExpensesExpenseIdEditRoute:
    GroupsGroupIdExpensesExpenseIdEditRoute,
  GroupsGroupIdExpensesExpenseIdIndexRoute:
    GroupsGroupIdExpensesExpenseIdIndexRoute,
}

const GroupsGroupIdExpensesRouteWithChildren =
  GroupsGroupIdExpensesRoute._addFileChildren(
    GroupsGroupIdExpensesRouteChildren,
  )

interface GroupsGroupIdRouteRouteChildren {
  GroupsGroupIdActivityRoute: typeof GroupsGroupIdActivityRoute
  GroupsGroupIdBalancesRoute: typeof GroupsGroupIdBalancesRoute
  GroupsGroupIdBudgetsRoute: typeof GroupsGroupIdBudgetsRouteWithChildren
  GroupsGroupIdEditRoute: typeof GroupsGroupIdEditRoute
  GroupsGroupIdExpensesRoute: typeof GroupsGroupIdExpensesRouteWithChildren
  GroupsGroupIdInformationRoute: typeof GroupsGroupIdInformationRoute
  GroupsGroupIdMembersRoute: typeof GroupsGroupIdMembersRoute
  GroupsGroupIdStatsRoute: typeof GroupsGroupIdStatsRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
}

const GroupsGroupIdRouteRouteChildren: GroupsGroupIdRouteRouteChildren = {
  GroupsGroupIdActivityRoute: GroupsGroupIdActivityRoute,
  GroupsGroupIdBalancesRoute: GroupsGroupIdBalancesRoute,
  GroupsGroupIdBudgetsRoute: GroupsGroupIdBudgetsRouteWithChildren,
  GroupsGroupIdEditRoute: GroupsGroupIdEditRoute,
  GroupsGroupIdExpensesRoute: GroupsGroupIdExpensesRouteWithChildren,
  GroupsGroupIdInformationRoute: GroupsGroupIdInformationRoute,
  GroupsGroupIdMembersRoute: GroupsGroupIdMembersRoute,
  GroupsGroupIdStatsRoute: GroupsGroupIdStatsRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
}

const GroupsGroupIdRouteRouteWithChildren =
  GroupsGroupIdRouteRoute._addFileChildren(GroupsGroupIdRouteRouteChildren)

interface GroupsRouteRouteChildren {
  GroupsGroupIdRouteRoute: typeof GroupsGroupIdRouteRouteWithChildren
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsImportRoute: typeof GroupsImportRoute
  GroupsBulkCategorizeGroupIdRoute: typeof GroupsBulkCategorizeGroupIdRoute
}

const GroupsRouteRouteChildren: GroupsRouteRouteChildren = {
  GroupsGroupIdRouteRoute: GroupsGroupIdRouteRouteWithChildren,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsImportRoute: GroupsImportRoute,
  GroupsBulkCategorizeGroupIdRoute: GroupsBulkCategorizeGroupIdRoute,
}

const GroupsRouteRouteWithChildren = GroupsRouteRoute._addFileChildren(
  GroupsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRouteRoute: GroupsRouteRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  FeedbackRoute: FeedbackRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthRecoverRoute: AuthRecoverRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  FriendsCreateRoute: FriendsCreateRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthLoginRoute: OauthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
