import { TRPCError } from '@trpc/server'
import { z } from 'zod'

import { expenseApiSchema } from '@spliit/domain'

import {
  compensateImportAttempt,
  deleteImportTempSources,
  ExpenseFileImportDuplicateError,
  findExpenseFileImportDuplicates,
  importExpenseFile,
  logImportOutcome,
  prepareExpenseFileImport,
  type ExpenseFileImportRow,
  type PreparedExpenseFileImport,
} from '../../../../lib/api/expenses/csv-import'
import {
  CREATE_OPERATIONS,
  createRequestIdSchema,
  runIdempotentCreate,
} from '../../../../lib/api/idempotency'
import { enqueueBudgetEvaluation } from '../../../../lib/budgets/enqueue'
import { ConversionError } from '../../../../lib/expense-conversion'
import { loadGroupMutationContext, protectedProcedure } from '../../../init'
import {
  expenseFileImportDuplicatesOutputSchema,
  expenseFileImportOutputSchema,
} from '../../../outputs/csv-import'

const expenseFileSourceSchema = z.object({
  baseFingerprint: z.string().regex(/^[0-9a-f]{64}$/),
  originFingerprint: z.string().regex(/^[0-9a-f]{64}$/),
})

const MAX_DOCUMENTS_PER_ROW = 10
// No per-row cap on approved keys: detection is exhaustive, and the UI's
// "Import anyway" approves every match a row reports — a per-row limit would
// turn the offered action into a guaranteed validation failure past N
// matches. Amplification is bounded by the 50_000 total below instead.
const MAX_APPROVED_DUPLICATE_KEYS_TOTAL = 50_000

const expenseFileImportRowSchema = z
  .object({
    rowId: z.string().trim().min(1).max(100),
    rowNumber: z.number().int().positive(),
    source: expenseFileSourceSchema,
    externalId: z.string().trim().min(1).max(200).nullish(),
    sourceAccount: z.string().trim().min(1).max(200).nullish(),
    expense: expenseApiSchema,
    approvedDuplicateKeys: z.array(z.string().min(1).max(200)).optional(),
  })
  .superRefine((row, context) => {
    // The shared documents schema is unbounded; this batch endpoint applies
    // its own resource budget. Review drafts start with empty
    // documents, but full-form edits and API-constructed payloads may attach
    // files up to this cap. This is an import-specific limit, not a limit
    // imposed by the ordinary single-expense form.
    const documentCount = row.expense.documents?.length ?? 0
    if (documentCount > MAX_DOCUMENTS_PER_ROW) {
      context.addIssue({
        code: 'custom',
        path: ['expense', 'documents'],
        message: `Documents per row exceeds the limit of ${MAX_DOCUMENTS_PER_ROW}`,
      })
    }
  })

/**
 * Row identity is generated by the browser, but it is still part of the API
 * boundary. Rejecting duplicate identities here prevents a malformed or
 * replayed payload from overwriting the deterministic row-to-expense map in the
 * bulk importer and makes the all-or-nothing guarantee explicit.
 */
const expenseFileImportRowsSchema = z
  .array(expenseFileImportRowSchema)
  .min(1)
  .max(10_000)
  .superRefine((rows, context) => {
    const seenRowIds = new Map<string, number>()
    const seenRowNumbers = new Map<number, number>()
    const seenOriginFingerprints = new Map<string, number>()

    for (const [index, row] of rows.entries()) {
      const previousRowId = seenRowIds.get(row.rowId)
      if (previousRowId !== undefined) {
        context.addIssue({
          code: 'custom',
          path: [index, 'rowId'],
          message: `Row ID is duplicated (also used by row ${previousRowId + 1})`,
        })
      } else {
        seenRowIds.set(row.rowId, index)
      }

      const previousRowNumber = seenRowNumbers.get(row.rowNumber)
      if (previousRowNumber !== undefined) {
        context.addIssue({
          code: 'custom',
          path: [index, 'rowNumber'],
          message: `Source row number is duplicated (also used at payload row ${previousRowNumber + 1})`,
        })
      } else {
        seenRowNumbers.set(row.rowNumber, index)
      }

      const previousOrigin = seenOriginFingerprints.get(
        row.source.originFingerprint,
      )
      if (previousOrigin !== undefined) {
        context.addIssue({
          code: 'custom',
          path: [index, 'source', 'originFingerprint'],
          message: `Origin fingerprint is duplicated (also used at payload row ${previousOrigin + 1})`,
        })
      } else {
        seenOriginFingerprints.set(row.source.originFingerprint, index)
      }
    }

    // Bound nested-payload amplification: rows are capped at 10_000 above and
    // each expense caps `items` at 100 in `expenseApiSchema`. A payload of
    // 10_000 rows × 100 items would still be 1M nested rows, so enforce a
    // total budget across the batch. Review drafts carry no items, but
    // full-form edits and API-constructed payloads may include them.
    const totalItems = rows.reduce(
      (sum, row) => sum + (row.expense.items?.length ?? 0),
      0,
    )
    if (totalItems > 20_000) {
      context.addIssue({
        code: 'custom',
        message: 'Total items across rows exceeds the limit of 20_000',
      })
    }

    // Same amplification concern one level down: `paidFor`/`paidByList`
    // arrays have no per-row cap (top-level `paidFor` even allows duplicate
    // participant ids), and each item carries its own `paidFor`. A single
    // participant id repeated millions of times would otherwise fan out
    // into millions of split rows inside one interactive transaction.
    const totalSplitEntries = rows.reduce(
      (sum, row) =>
        sum +
        (row.expense.paidByList?.length ?? 0) +
        (row.expense.paidFor?.length ?? 0) +
        (row.expense.items ?? []).reduce(
          (itemSum, item) => itemSum + (item.paidFor?.length ?? 0),
          0,
        ) +
        (row.expense.itemizedRemainder?.paidFor?.length ?? 0),
      0,
    )
    if (totalSplitEntries > 200_000) {
      context.addIssue({
        code: 'custom',
        message: 'Total split entries across rows exceeds the limit of 200_000',
      })
    }

    const totalDocuments = rows.reduce(
      (sum, row) => sum + (row.expense.documents?.length ?? 0),
      0,
    )
    if (totalDocuments > 20_000) {
      context.addIssue({
        code: 'custom',
        message: 'Total documents across rows exceeds the limit of 20_000',
      })
    }

    const totalApprovedKeys = rows.reduce(
      (sum, row) => sum + (row.approvedDuplicateKeys?.length ?? 0),
      0,
    )
    if (totalApprovedKeys > MAX_APPROVED_DUPLICATE_KEYS_TOTAL) {
      context.addIssue({
        code: 'custom',
        message:
          'Total approved duplicate keys across rows exceeds the limit of 50_000',
      })
    }
  })

const expenseFileImportInputSchema = z.object({
  groupId: z.string().min(1),
  rows: expenseFileImportRowsSchema,
})

/**
 * Custom-currency ledgers (null `currencyCode`) are valid for same-currency
 * imports — the lib resolves them without FX. Only EXCHANGE conversions need an
 * ISO ledger base, so only reject null ledgers when a row actually needs one.
 */
function rowsNeedExchangeLedger(
  rows: Array<{ expense?: { conversion?: { type?: string } | null } }>,
): boolean {
  return rows.some((row) => row.expense?.conversion?.type === 'exchange')
}

export const previewExpenseFileImportDuplicatesProcedure = protectedProcedure
  .input(expenseFileImportInputSchema)
  .output(expenseFileImportDuplicatesOutputSchema)
  .mutation(async ({ input, ctx }) => {
    const { group, ledger } = await loadGroupMutationContext({
      groupId: input.groupId,
      accountId: ctx.auth.user.id,
    })
    if (group.archived) {
      throw new TRPCError({
        code: 'FORBIDDEN',
        message: 'This group is archived and cannot accept imports',
        cause: { code: 'IMPORT_GROUP_ARCHIVED_CANNOT_ACCEPT', params: {} },
      })
    }
    if (!ledger.currencyCode && rowsNeedExchangeLedger(input.rows)) {
      throw new TRPCError({
        code: 'BAD_REQUEST',
        message:
          'Expense file imports require an ISO currency code for the group',
        cause: { code: 'IMPORT_LEDGER_CURRENCY_REQUIRED', params: {} },
      })
    }
    const rows = input.rows as ExpenseFileImportRow[]
    const { rows: duplicates } = await findExpenseFileImportDuplicates(
      ledger.id,
      ledger.currencyCode ?? null,
      rows,
    )
    return { rows: duplicates }
  })

export const importExpenseFileProcedure = protectedProcedure
  .input(
    z.object({
      requestId: createRequestIdSchema,
      groupId: z.string().min(1),
      rows: expenseFileImportRowsSchema,
    }),
  )
  .output(expenseFileImportOutputSchema)
  .mutation(async ({ input, ctx }) => {
    const { group, ledger } = await loadGroupMutationContext({
      groupId: input.groupId,
      accountId: ctx.auth.user.id,
    })
    if (group.archived) {
      throw new TRPCError({
        code: 'FORBIDDEN',
        message: 'This group is archived and cannot accept imports',
        cause: { code: 'IMPORT_GROUP_ARCHIVED_CANNOT_ACCEPT', params: {} },
      })
    }
    if (!ledger.currencyCode && rowsNeedExchangeLedger(input.rows)) {
      throw new TRPCError({
        code: 'BAD_REQUEST',
        message:
          'Expense file imports require an ISO currency code for the group',
        cause: { code: 'IMPORT_LEDGER_CURRENCY_REQUIRED', params: {} },
      })
    }

    try {
      // This call site owns the transaction settings: large file imports
      // hold the group lock across bulk writes, so they opt into a bounded
      // 120s timeout (the database default is 5s). Ordinary creates omit
      // `transaction` and keep the defaults.
      //
      // Outcome logs emit from this owner, never from inside the write
      // transaction: `committed` via onSuccess (fresh commits only — replays
      // skip it, and the originating attempt already logged), `failed` via
      // the catch below. `preparedRef` bridges the write-pass timings for
      // the failure case.
      let preparedRef: PreparedExpenseFileImport | undefined
      // The failure log below is scoped to the import itself: a later
      // budget-enqueue failure must not rewrite an already-logged commit.
      const { value } = await runIdempotentCreate({
        accountId: ctx.auth.user.id,
        operation: CREATE_OPERATIONS.expenseFileImport,
        requestId: input.requestId,
        input: { groupId: input.groupId, rows: input.rows },
        transaction: { timeout: 120_000, maxWait: 30_000 },
        prepare: async () =>
          (preparedRef = await prepareExpenseFileImport(
            input.groupId,
            ctx.auth.user.id,
            input.rows as ExpenseFileImportRow[],
          )),
        execute: (tx, prepared) =>
          importExpenseFile(
            {
              groupId: input.groupId,
              accountId: ctx.auth.user.id,
              rows: input.rows as ExpenseFileImportRow[],
            },
            { tx, prepared },
          ),
        // Compensation covers the whole owned transaction: execution
        // failures, idempotency-result update failures, commit failures,
        // and lost creation races. Staged sources are removed after a
        // known-good commit so failures stay retryable.
        compensate: (prepared) => compensateImportAttempt(prepared),
        onSuccess: async (prepared) => {
          logImportOutcome(prepared, { committed: true })
          await deleteImportTempSources(prepared)
        },
      }).catch((error: unknown) => {
        logImportOutcome(preparedRef, { committed: false, error })
        throw error
      })
      // Budget evaluation is idempotency-safe (singleton-keyed queue job that
      // no-ops when the queue is unavailable), so it must run even when the
      // stored idempotent result is replayed. Skipping it on replay would
      // leave budgets stale after a client retry.
      await enqueueBudgetEvaluation(input.groupId)
      return value
    } catch (error) {
      if (error instanceof ExpenseFileImportDuplicateError) {
        // Transport note: tRPC v11.18's default error shape carries only
        // `message`/`code`/`data` (the `errorFormatter` in `trpc/init.ts`
        // forwards a stable `{ code, params }` pair from `cause` into
        // `data.importCode`/`data.importParams` for HTTP clients, and keeps
        // the full `cause` for in-process callers). `conflicts` below stays
        // in-process only (plain JSON {rowId, rowNumber, matchKeys}): tests,
        // server logs, and createCaller consumers read actionable keys off
        // it. HTTP clients recover the same keys via
        // `previewImportDuplicates` — that is what the web importer does (its
        // commit catch translates `data.importCode` when present and
        // otherwise falls back to `message`, then re-runs the duplicate
        // check), so nothing else needs to change.
        throw new TRPCError({
          code: 'CONFLICT',
          message: error.message,
          cause: {
            code: 'IMPORT_DUPLICATE_CONFLICT',
            params: {
              rows: error.conflicts
                .map((conflict) => conflict.rowNumber)
                .join(', '),
            },
            conflicts: error.conflicts,
          },
        })
      }
      if (error instanceof TRPCError) throw error
      if (error instanceof ConversionError) {
        throw new TRPCError({
          code:
            error.code === 'PROVIDER_UNAVAILABLE'
              ? 'BAD_GATEWAY'
              : 'BAD_REQUEST',
          message: error.message,
        })
      }
      throw error
    }
  })
