import { Scalar } from '@scalar/hono-api-reference'
import { TRPCError } from '@trpc/server'
import { fetchRequestHandler } from '@trpc/server/adapters/fetch'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { readFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { auth } from './lib/auth'
import { webOrigins } from './lib/env'
import { checkLiveness, checkReadiness } from './lib/health'
import { logServerError, logServerWarn } from './lib/logging'
import { buildScalarConfig } from './lib/scalar-theme'
import { exportGroupCsv } from './routes/export-csv'
import { exportGroupJson } from './routes/export-json'
import { createTRPCContext } from './trpc/init'
import { appRouter } from './trpc/routers/_app'

const __dirname = dirname(fileURLToPath(import.meta.url))
// Resolve the generated OpenAPI spec relative to the compiled/running
// file so it works for both `bun run src/server.ts` (dev) and a future
// bundled deployment.
const openapiSpecPath = resolve(__dirname, '..', 'openapi.json')

export const app = new Hono()

// Centralised handler for any uncaught error outside `/trpc/*`. tRPC has its
// own error pipeline (see `onError` on fetchRequestHandler below) so this
// only fires for non-tRPC routes — auth, uploads, exports, currency, health.
app.onError((err, c) => {
  const path = c.req.path
  // Health probes are polled constantly; surface only unexpected failures
  // through the centralised log to avoid noise. The health handler itself
  // already returns a structured payload with its own error info.
  if (path.startsWith('/health')) {
    logServerWarn('api.health', err, { method: c.req.method, path })
    return c.json({ status: 'error' }, 500)
  }
  logServerError('api', err, { method: c.req.method, path })
  return c.json({ status: 'error' }, 500)
})

app.use(
  '*',
  cors({
    origin: (origin) => {
      if (!origin) return origin
      return webOrigins.includes(origin) ? origin : ''
    },
    allowHeaders: ['Content-Type', 'Authorization', 'trpc-accept'],
    allowMethods: ['GET', 'POST', 'OPTIONS'],
    credentials: true,
  }),
)

app.get('/health', () => checkLiveness())
app.get('/health/liveness', () => checkLiveness())
app.get('/health/readiness', () => checkReadiness())

// better-auth handler — exposes /auth/sign-in, /auth/sign-up, etc.
app.on(['GET', 'POST'], '/auth/*', (c) => auth.handler(c.req.raw))

app.get('/groups/:groupId/expenses/export/json', (c) =>
  exportGroupJson(c.req.raw, c.req.param('groupId')),
)
app.get('/groups/:groupId/expenses/export/csv', (c) =>
  exportGroupCsv(c.req.raw, c.req.param('groupId')),
)

// Public OpenAPI spec served at /openapi.json. The file is generated by
// `bun generate-openapi` (Turbo task `generate-openapi`); if it's missing
// the route 404s with a clear hint instead of crashing the server.
app.get('/openapi.json', async (c) => {
  try {
    const body = await readFile(openapiSpecPath, 'utf8')
    return c.json(JSON.parse(body))
  } catch (err) {
    logServerWarn('api.openapi', err, { path: '/openapi.json' })
    return c.json(
      {
        error:
          'OpenAPI spec not generated. Run `bun generate-openapi` (or `bun run generate-openapi` in apps/api) to produce apps/api/openapi.json.',
      },
      404,
    )
  }
})

// Scalar-hosted API reference at /docs, fed from the same spec. The
// browser fetches /openapi.json itself, so we don't need to inline the
// document here. Brand theming (favicon, accent color, dark mode,
// disabled hosted Agent) lives in `lib/scalar-theme.ts`.
app.get(
  '/docs',
  Scalar({
    url: '/openapi.json',
    ...buildScalarConfig(),
  }),
)

app.all('/trpc/*', (c) =>
  fetchRequestHandler({
    endpoint: '/trpc',
    req: c.req.raw,
    router: appRouter,
    createContext: () => createTRPCContext({ req: c.req.raw }),
    onError({ error, path, type, ctx }) {
      // Expected client errors are normal product behavior — logging them
      // would flood the console. Only log infrastructure failures (uncaught
      // exceptions turned into INTERNAL_SERVER_ERROR) and upstream-provider
      // failures (BAD_GATEWAY), plus any non-TRPCError that escaped a
      // procedure.
      const code = error.code
      const isExpected =
        error instanceof TRPCError &&
        (code === 'UNAUTHORIZED' ||
          code === 'FORBIDDEN' ||
          code === 'NOT_FOUND' ||
          code === 'BAD_REQUEST' ||
          code === 'PRECONDITION_FAILED' ||
          code === 'CONFLICT' ||
          code === 'TOO_MANY_REQUESTS')
      if (isExpected) return

      const accountId = ctx?.auth?.user?.id
      logServerError(
        'trpc',
        error,
        accountId ? { path, type, code, accountId } : { path, type, code },
      )
    },
  }),
)
