#!/usr/bin/env bun
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  parseAnnouncementFile,
  validateAnnouncementBody,
} from '../packages/domain/src/announcements/markdown'
import { isSparseLocale, locales as domainLocales } from '../packages/domain/src/i18n'

const root = fileURLToPath(new URL('../', import.meta.url))
const announcementsDir = join(root, 'packages/domain/src/announcements')
const outputPath = join(
  root,
  'packages/domain/src/announcement-content.generated.ts',
)

type Entry = {
  id: string
  date: string
  title: string
  inApp: boolean
  email: boolean
  locales: Record<string, { title: string; body: string }>
}

function isDirectory(path: string): boolean {
  try {
    return statSync(path).isDirectory()
  } catch {
    return false
  }
}

function build(): { entries: Entry[]; source: string } {
  const ids = readdirSync(announcementsDir).filter((name) => {
    if (name.endsWith('.ts')) return false
    return isDirectory(join(announcementsDir, name))
  })
  const entries: Entry[] = []
  for (const id of sorted(ids)) {
    const dir = join(announcementsDir, id)
    const files = readdirSync(dir).filter((f) => f.endsWith('.md'))
    if (!files.includes('en-US.md')) {
      throw new Error(`Announcement ${id} is missing required en-US.md`)
    }
    // Announcements ship only with full locale coverage: every full-bundle
    // locale needs its own file (sparse overlays inherit at runtime).
    const missing = domainLocales.filter(
      (locale) =>
        locale !== 'en-US' &&
        !isSparseLocale(locale) &&
        !files.includes(`${locale}.md`),
    )
    if (missing.length > 0) {
      throw new Error(
        `Announcement ${id} is missing locale files: ${missing.join(', ')}`,
      )
    }
    const locales: Entry['locales'] = {}
    let reference: Entry | null = null
    for (const file of sorted(files)) {
      const locale = file.replace(/\.md$/, '')
      const raw = readFileSync(join(dir, file), 'utf8')
      const { frontmatter, body } = parseAnnouncementFile(raw)
      if (frontmatter.id !== id) {
        throw new Error(
          `Frontmatter id ${frontmatter.id} does not match folder ${id}`,
        )
      }
      validateAnnouncementBody(body)
      if (!reference) {
        reference = {
          id,
          date: frontmatter.date,
          title: frontmatter.title,
          inApp: frontmatter.inApp,
          email: frontmatter.email,
          locales: {},
        }
      } else {
        if (
          frontmatter.date !== reference.date ||
          frontmatter.inApp !== reference.inApp ||
          frontmatter.email !== reference.email
        ) {
          throw new Error(
            `Frontmatter date/inApp/email must match en-US for ${id}:${locale}`,
          )
        }
      }
      locales[locale] = { title: frontmatter.title, body }
    }
    const ref = reference!
    // en-US title is the registry title
    const enTitle = locales['en-US']!.title
    entries.push({
      id: ref.id,
      date: ref.date,
      title: enTitle,
      inApp: ref.inApp,
      email: ref.email,
      locales,
    })
  }
  entries.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0))
  const registry = entries.map(({ locales: _locales, ...rest }) => rest)
  const contents: Record<string, { title: string; body: string }> = {}
  for (const entry of entries) {
    for (const [locale, content] of Object.entries(entry.locales)) {
      contents[`${entry.id}:${locale}`] = content
    }
  }
  const source =
    `// Generated by bun scripts/generate-announcement-content.ts. Do not edit.\n` +
    `export const announcements = ${JSON.stringify(registry, null, 2)} as const\n` +
    `export const announcementContents = ${JSON.stringify(contents, null, 2)} as const\n`
  return { entries, source }
}

function sorted<T>(values: T[]): T[] {
  return [...values].sort()
}

const { source } = build()
if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== source) {
    throw new Error(
      'Announcement content is stale; run bun scripts/generate-announcement-content.ts',
    )
  }
} else {
  writeFileSync(outputPath, source)
}
