export type { ServiceError } from './errors'
export {
  CapabilityError,
  GroupDeniedError,
  HttpError,
  isOfflineProof,
  isServerAnswer,
  isServiceError,
  NetworkError,
  PermissionError,
  RateLimitError,
  SessionRejectedError,
  StaleGenerationError,
  StaleLeaseError,
  StaleRevisionError,
  StorageBlockedError,
  StorageCorruptError,
  StorageQuotaError,
  StorageSchemaError,
  StorageUnavailableError,
  TimeoutError,
  UploadError,
  WorkerError,
} from './errors'
export {
  AppStatusService,
  INITIAL_APP_STATUS,
  makeAppStatus,
  type AppStatusService as AppStatusServiceShape,
  type AppStatusSnapshot,
  type SessionScopeStatus,
} from './app-status'
export {
  HealthProbe,
  makeHealthProbe,
  nextProbeDelayMs,
  toProbeOutcomeForResponse,
  transportForOutcome,
  type HealthProbe as HealthProbeShape,
  type HealthProbeDeps,
  type ProbeOutcome,
} from './health'
export {
  AppServicesLive,
  AppStatusLive,
  FetchTransportLive,
  makeAppRuntime,
  makeAppStatusLive,
  makeFetchTransportLive,
  makeHealthProbeLive,
  PlatformClockLive,
  TransportAdapterLive,
  type AppServices,
} from './layers'
export {
  mapToConnectivityStatus,
  mapToPersistedCode,
  safeMessageForLog,
} from './outcomes'
export {
  FetchTransport,
  FETCH_DEFAULT_TIMEOUT_MS,
  makeFetchTransport,
  PlatformClock,
  RATE_LIMIT_DEFAULT_RETRY_AFTER_MS,
  classifyFetchRejection,
  classifyHttpStatus,
  parseRetryAfterMs,
  type FetchTransport as FetchTransportShape,
  type FetchRequestOptions,
  type FetchTransportDeps,
  type FetchTransportError,
  type PlatformClock as PlatformClockShape,
} from './platform'
export {
  SessionService,
  applyVerdictToScope,
  makeSessionService,
  probeResultToVerdict,
  sessionRejectedFromStatus,
  type SessionProbeAccount,
  type SessionProbeResult,
  type SessionScope,
  type SessionService as SessionServiceShape,
  type SessionServiceDeps,
  type SessionVerification,
  type SessionVerdict,
} from './session'
export {
  createSnapshotBridge,
  useServiceSnapshot,
  type SnapshotBridge,
} from './snapshot'
export {
  AccountSupervisor,
  INITIAL_SUPERVISOR,
  isCurrentGeneration,
  makeAccountSupervisor,
  makeAccountSupervisorLive,
  reduceSupervisorEvent,
  type AccountIdentity,
  type AccountSupervisor as AccountSupervisorShape,
  type AccountSupervisorDeps,
  type SupervisorSnapshot,
  type SupervisorStatus,
} from './account-supervisor'
export {
  checkAdmission,
  admitMutationEffect,
  classifyMutationOutcome,
  ensureRequestId,
  IDEMPOTENCY_HEADER,
  withIdempotencyHeader,
  type AdmissionInput,
  type AdmissionVerdict,
  type MutationOutcome,
} from './admission'
export {
  makeProbeOrchestrator,
  PROBE_RECOVERY_ATTEMPTS,
  ProbeOrchestrator,
  ProbeOrchestratorLive,
  recoveryDelayMs,
  type ProbeOrchestrator as ProbeOrchestratorShape,
  type ProbeOrchestratorDeps,
} from './probe-orchestrator'
export {
  bootstrapPageRuntime,
  disposePageRuntime,
  getPageRuntime,
  usePageRuntime,
  wirePageStarters,
  type PageRuntime,
  type PageStarters,
} from './runtime'
export {
  makeBetterAuthFetchSession,
  makeSessionServiceLive,
  readRestorableAccount,
  revokeIdentitySync,
  SessionServiceLive,
  toSessionProbeResult,
  type GetSessionFn,
  type RestorableIdentity,
} from './session-integration'
export {
  attemptPublish,
  fenceGuard,
  makeWorkerRuntime,
  scopeForEvent,
  type FencedPublish,
  type WorkerRuntime,
} from './worker-lifecycle'
export {
  OfflineStorage,
  makeOfflineStorage,
  makeOfflineStorageLive,
  mapStorageError,
  type OfflineStorage as OfflineStorageShape,
  type OfflineStorageOpenDeps,
  type StorageServiceError,
} from './offline-storage'
export {
  OfflineReads,
  makeOfflineReads,
  mapReadError,
  type OfflineReads as OfflineReadsShape,
  type OfflineReadQueryOptions,
  type OfflineReadsDeps,
  type ReadServiceError,
} from './offline-reads'
export {
  OfflineDownloads,
  makeOfflineDownloads,
  type OfflineDownloads as OfflineDownloadsShape,
  type OfflineDownloadDeps,
} from './offline-downloads'
export {
  createEffectFetch,
  EFFECT_BRIDGE_QUERY_DEFAULTS,
  probeOutcomeForFetchEvent,
  reportFetchOutcomeToLegacyStore,
  reportFetchOutcomeToServices,
  transportForFetchEvent,
  type EffectFetchDeps,
  type FetchReportEvent,
} from './transport-integration'
export {
  makePwaInstallService,
  makePwaInstallServiceLive,
  selectInstallReady,
  selectShouldPromote,
  INSTALL_DISMISS_KEY,
  INSTALL_REMIND_KEY,
  PwaInstallService,
  type PromotionGates,
  type PwaInstallService as PwaInstallServiceShape,
  type PwaInstallServiceDeps,
  type PwaInstallSnapshot,
} from './pwa-install'
export {
  makePwaNotificationService,
  makePwaNotificationServiceLive,
  NOTIFICATION_NAV_ACK_TIMEOUT_MS,
  PwaNotificationService,
  type NotificationClickDeps,
  type NotificationClickInput,
  type PwaNotificationPageDeps,
  type PwaNotificationPageSnapshot,
  type PwaNotificationService as PwaNotificationServiceShape,
} from './pwa-notifications'
export {
  makePwaPersistence,
  makePwaPersistenceLive,
  PWA_PERSIST_ATTEMPT_KEY,
  PwaPersistenceService,
  type PwaPersistenceDeps,
  type PwaPersistenceService as PwaPersistenceServiceShape,
  type PwaPersistenceSnapshot,
} from './pwa-persistence'
export {
  makePwaUpdateService,
  makePwaUpdateServiceLive,
  PWA_UPDATE_CHECK_INTERVAL_MS,
  PwaUpdateService,
  type PwaUpdateCheckSnapshot,
  type PwaUpdateService as PwaUpdateServiceShape,
  type PwaUpdateServiceDeps,
  type PwaUpdateServiceSnapshot,
  type PwaUpdateTrigger,
} from './pwa-updates'
export {
  createPwaPageServices,
  requestPwaPersistence,
  type PwaPageDeps,
  type PwaPageServices,
} from './pwa-wiring'
export {
  AuthFlows,
  makeAuthFlows,
  makeAuthFlowsLive,
  type AuthAccountInfo,
  type AuthFailureCode,
  type AuthFlowDeps,
  type AuthFlows as AuthFlowsShape,
  type AuthResult,
  type CommandResult,
  type PasswordCredentials,
  type SdkError,
} from './auth-flows'
export {
  DocumentRecovery,
  makeDocumentRecovery,
  makeDocumentRecoveryLive,
  DOCUMENT_STAGING_TIMEOUT_MS,
  type DocumentRecovery as DocumentRecoveryShape,
  type DocumentRecoveryDeps,
  type RecoveryDocument,
  type RecoveryFailure,
  type RecoveryOutcome,
  type RecoverySnapshot,
  type StagedDocument,
} from './import-recovery'
export {
  makePreferencesSync,
  makePreferencesSyncLive,
  INITIAL_PREFERENCES,
  PreferencesSyncService,
  type PatchOptions,
  type PatchResult,
  type PreferencesSnapshot,
  type PreferencesSyncDeps,
  type PreferencesSyncService as PreferencesSyncServiceShape,
  type PreferencePatch,
} from './preferences-sync'
export {
  makePushService,
  makePushServiceLive,
  INITIAL_PUSH,
  PushService,
  type EnableOutcome,
  type PushFailure,
  type PushPermissionState,
  type PushService as PushServiceShape,
  type PushServiceDeps,
  type PushSnapshot,
  type PushSubscriptionRecord,
} from './push'
export {
  makeUploadPipeline,
  makeUploadPipelineLive,
  UploadPipeline,
  type PreparedFile,
  type PresignResult,
  type UploadDone,
  type UploadFailure,
  type UploadInput,
  type UploadOutcome,
  type UploadPipeline as UploadPipelineShape,
  type UploadPipelineDeps,
  type UploadUnknown,
} from './uploads'
